# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAngin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.CharField(max_length=100, verbose_name='Tanggal Pengukuran')),
                ('waktu', models.CharField(max_length=100, verbose_name='Waktu Pengukuran')),
                ('arah', models.FloatField(verbose_name='Arah Angin (satuan sudut)')),
                ('kompas', models.CharField(max_length=3, verbose_name='Simbol Arah (kompas)')),
                ('kecepatan', models.FloatField(verbose_name='Kecepatan Angin (m/s)')),
                ('grup_kecepatan', models.FloatField(verbose_name='Kelompok Kecepatan Angin (m/s)')),
                ('akselerator1', models.FloatField(verbose_name='Akselerator 1')),
                ('akselerator2', models.FloatField(verbose_name='Akselerator 2')),
                ('akselerator3', models.FloatField(verbose_name='Akselerator 3')),
                ('akselerator4', models.FloatField(verbose_name='Akselerator 4')),
                ('akselerator5', models.FloatField(verbose_name='Akselerator 5')),
            ],
        ),
    ]
