# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataangin',
            name='tanggal',
            field=models.DateField(verbose_name='Tanggal Pengukuran'),
        ),
        migrations.AlterField(
            model_name='dataangin',
            name='waktu',
            field=models.TimeField(max_length=100, verbose_name='Waktu Pengukuran'),
        ),
    ]
