# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_pilihanvisualisasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaerahObjek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_objek', models.CharField(max_length=200, verbose_name='Nama Observasi Objek')),
                ('nama_daerah', models.CharField(max_length=100, verbose_name='Daerah')),
            ],
        ),
        migrations.AddField(
            model_name='dataangin',
            name='daerah',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.DaerahObjek', verbose_name='Daerah'),
        ),
    ]
