# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20160225_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilihanvisualisasi',
            name='daerah',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.DaerahObjek', verbose_name='Daerah'),
        ),
    ]
