# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20170314_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataangin',
            options={'ordering': ('tanggal', 'waktu')},
        ),
    ]
